# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c07425e6162e19b28bf21d462e21f4b1d3593b84e0236e8f487a08362eefb93e86e4a5a68c7cf5f81396756fbd39e501e1b1485d47edeae79f68052fc46eb47c

test:
  secret_key_base: 983fd65ffb5308ba8c7494695984285de1877b6d6de78bd15a7d24eb797e1883ad989c95314537e74a74ad90780e899742de20f7c924e2e1b6895d0b3da44c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
